"""Nova coluna Tamanhos

Revision ID: 4e8e02a0e149
Revises: 950f193956b2
Create Date: 2024-03-28 20:55:20.453681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8e02a0e149'
down_revision: Union[str, None] = '950f193956b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tamanhos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'tamanhos')
    # ### end Alembic commands ###
